include: package:flutter_lints/flutter.yaml

analyzer: 
  exclude: [
    "**/*.g.dart",
    "**/*.freezed.dart",
    "**/*.config.dart"
  ]

linter:
  rules:
    prefer_relative_imports: true
    use_super_parameters: true
