name: shopping_list
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  freezed_annotation: ^2.0.3
  get_it: ^7.2.0
  google_fonts: ^2.3.2
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  html: ^0.15.0
  http: ^0.13.4
  injectable: ^1.5.3
  intl: ^0.17.0
  mobile_scanner: ^1.1.1
  quiver: ^3.1.0
  rxdart: ^0.27.3
  shared_preferences: ^2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  freezed: ^2.0.3
  build_runner: ^2.1.10
  hive_generator: ^1.1.2
  injectable_generator: ^1.5.3

flutter:
  uses-material-design: true

  assets:
    - assets/
